### PR TITLE
Fix Travis build, update dependencies (execept selenium-webdriver)

### LINKED ISSUE #13: Fix .travis-setup.sh
Hey,

So after we discussed it with @tripu, it appeared that we need to fix the `.travis-setup.sh`. `sudo` is not possible anymore on travis. So it's getting harder to install chrome.

So we have 2 possibilities:
- Travis supports firefox. It's pre-installed on it. We switch to Firefox -> fixed
- We try to find a pre-compiled version of chrome, or create one, upload it somewhere and use it on travis

@dontcallmedom what do you think?

### PR DESCRIPTION
**Pull request by qwertychouskie**
Closes #13
May be needed for https://github.com/w3c/Mobile-Checker/pull/140

### CODE REVIEW

**Comment by qwertychouskie** [comment]
Getting close, 6/7 tests passing...

**Comment by qwertychouskie** [comment]
"Done. Your build exited with 0." Wooho! @dontcallmedom @tripu If one (or both) of you could make sure I didn't do anything wrong (especially in [browser-emulator-tests.js](https://github.com/w3c/mobile-web-browser-emulator/pull/15/files#diff-d094441bdfaa42119332480b2b541ed9), then merge the PR and push the update to NPM, that would be highly appreciated.

**Comment by qwertychouskie** [comment]
P.S. Probably merge as one commit :)

File: test/browser-emulator-tests.js [hunk 1]
```diff
@@ -20,19 +20,19 @@ describe("Starting and quiting browser", function() {
             done();
         });
         browser.open("file://" + __dirname + "/browser-tests/ok.html");
-        browser.close().then(done);
+        browser.close().then(done());
```
Comment (dontcallmedom) [inline test/browser-emulator-tests.js]: this is definitely wrong - this means `done` gets called as soon this code is read, when it is supposed to be fired when `browser.close()` finishes

Comment (qwertychouskie) [inline test/browser-emulator-tests.js]: Should be fixed in latest commit.

Comment (qwertychouskie) [inline test/browser-emulator-tests.js]: @dontcallmedom Should be fixed in latest commit.

Comment (dontcallmedom) [inline test/browser-emulator-tests.js]: sorry, I think I was unclear - `then(done)` is what needs to be made to work - the two other usage of `done` you've suggested hide the problem rather than fix the bug.

To be more specific - if `done()` is called before `browser.close()` terminates (which happens both with `b.close().then(done())` and `b.close(); done();`) then we don't test that the `close()` method properly resolve its promise - and since it doesn't, there is a bug that needs fixing, not hiding :)

Thanks

**Comment by tripu** [comment]
@qwertychouskie, may I suggest you add a `.gitignore` containing:

```
node_modules/
browsermob-proxy-2.1.4/
bmp.log
browsermob-proxy-2.0-beta-9
browsermob-proxy-2.1.4-bin.zip
```

?

File: test/browser-emulator-tests.js [hunk 2]
```diff
@@ -20,19 +20,20 @@ describe("Starting and quiting browser", function() {
...
             browsermobProxy: {
-                port: 8081
+                port: 9999
             },
             trackNetwork: true
         });
         browser.on('error', function(err) {
             expect(err.message).to.be(
-                'Failed gathering network traffic: Error: connect ECONNREFUSED'
+                'Failed gathering network traffic: Error: connect ECONNREFUSED 127.0.0.1:9999'
```
Comment (tripu) [inline test/browser-emulator-tests.js]: I had to change this IP address here to `127.0.1.1` (that's my `localhost`, don't ask me why :) to make this work. Apart from this, all tests run okay for me now.

Is there a way to make this more robust, and less dependant on the loopback?

Comment (qwertychouskie) [inline test/browser-emulator-tests.js]: Fixed in https://github.com/w3c/mobile-web-browser-emulator/pull/15/commits/1a8956ce53c07aa1b7a41c97ae7acbce5f7f73f1

File: test/browser-emulator-tests.js (hunk 1 above)
Comment (qwertychouskie) [inline test/browser-emulator-tests.js]: `done` is a variable passed to the `it()` function (see lines 12-13), so the way it was, `done()` (the function that ends the test) was never called.  Maybe:
```
browser.close().then(done);
done();
```

Comment (tripu) [inline test/browser-emulator-tests.js]: @qwertychouskie: the function `done` should be invoked when the promise returned by `close()` resolves; your change invokes it immediately. I think @dontcallmedom is right here.

File: test/browser-emulator-tests.js (hunk 2 above)
Comment (tripu) [inline test/browser-emulator-tests.js]: Ah, it was easy enough&nbsp;&mdash;&nbsp;I should have done it myself.
Thank you!

**Review by tripu — CHANGES_REQUESTED** [review]
There is a lot in `.gitignore` that we don't need. Can we keep it to the minimum, please?

**Comment by qwertychouskie** [comment]
@tripu I used GitHub's template for node projects.

File: test/browser-emulator-tests.js (hunk 1 above)
Comment (qwertychouskie) [inline test/browser-emulator-tests.js]: How should it be done then?  The way it was done before never worked: https://travis-ci.org/w3c/mobile-web-browser-emulator/builds

**Comment by tripu** [comment]
@qwertychouskie, templates are handy for quickly bootstrapping a project with a complex setup, I guess.
We know what we need; all those extra lines &ldquo;just in case&rdquo; are a bit noisy, IMHO.

**Comment by qwertychouskie** [comment]
Just removed all unneeded lines in .gitignore.

**Review by tripu — APPROVED** [review]
There are still a few lines I don't see necessary for us, but I don't want to hold this PR.
@dontcallmedom?

File: test/browser-emulator-tests.js (hunk 1 above)
Comment (dontcallmedom) [inline test/browser-emulator-tests.js]: I'm quite sure it used to work, although there may have been troubles reproducing that success on Travis (my memories are starting to be fuzzy).

In any case, I prefer a Travis build that fails for good reasons (here, the fact that the `browser.close` promise doesn't resolve correctly) rather than a Travis build that succeeds and hides bugs.

Can you revert that particular set of changes (back to `browser.close().then(done);`) so that we can merge the rest of excellent changes? Even if the Travis build still fails, it will be in a much better starting point

**Comment by dontcallmedom** [comment]
I would prefer we not merge the changes to `browser.close.then(done)` but otherwise, I'm eager to see this merged :)

Many thanks @qwertychouskie

**Comment by qwertychouskie** [comment]
Pushed another change, now uses:
```
browser.close().then(done);
done();
```

File: test/browser-emulator-tests.js [hunk 3]
```diff
@@ -20,7 +20,7 @@ describe("Starting and quiting browser", function() {
             done();
         });
         browser.open("file://" + __dirname + "/browser-tests/ok.html");
-        browser.close();
+        browser.close().then(done);
         done();
```
Comment (tripu) [inline test/browser-emulator-tests.js]: @qwertychouskie, I think these lines you added are still wrong&hellip;

```javascript
done();
```

**Review by tripu — CHANGES_REQUESTED** [review]
Please see last inline comment.

File: test/browser-emulator-tests.js (hunk 3 above)
Comment (qwertychouskie) [inline test/browser-emulator-tests.js]: All `done()`s removed.

**Review by tripu — APPROVED** [review]

**Comment by tripu** [comment]
Thank you, @qwertychouskie.
Back to @dontcallmedom.
